version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post123
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: ./backend
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:post123@db:5432/chat
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    depends_on:
      - api
    ports:
      - "5173:80" # optional direct preview
    volumes:
      - ./frontend:/app
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - frontend
    restart: unless-stopped

volumes:
  db-data:
